apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-attestation-config
  labels:
    {{- include "confidential-compute.labels" . | nindent 4 }}
data:
  attestation.conf: |
    {
      "attestation": {
        "enabled": {{ .Values.security.attestation.enabled }},
        "interval": "{{ .Values.security.attestation.interval }}",
        {{- if eq .Values.confidentialComputing.platform "sgx" }}
        "type": "sgx",
        "sgx_spid": "${SGX_SPID}",
        "ias_url": "{{ .Values.confidentialComputing.sgx.attestation.providerUrl }}"
        {{- else }}
        "type": "nitro",
        "aws_region": "${AWS_REGION}",
        "kms_key_id": "${KMS_KEY_ID}"
        {{- end }}
      }
    }
