apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secure-app
  labels:
    {{- include "confidential-compute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
